version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mitv-backend
    environment:
      - NODE_ENV=production
      - PORT=3001
    expose:
      - "3001"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - webnet

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mitv-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
