# backend Dockerfile
ARG BASE_NODE_IMAGE=node:20-slim
FROM ${BASE_NODE_IMAGE}

# 安装 adb
RUN apt-get update \
  && apt-get install -y --no-install-recommends android-tools-adb \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY backend/package.json ./
RUN npm i --omit=dev

COPY backend ./

ENV PORT=3001
EXPOSE 3001

CMD ["node", "app.js"]
