# frontend Dockerfile
FROM node:20-slim AS build
WORKDIR /app
COPY frontend/package.json ./
RUN npm i
COPY frontend ./
RUN npm run build

FROM nginx:1.27-alpine AS serve
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist ./
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
