services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        BASE_NODE_IMAGE: ${BASE_NODE_IMAGE:-node:20-slim}
    container_name: mitv-backend
    environment:
      - NODE_ENV=production
      - PORT=3001
    expose:
      - "3001"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - webnet

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        BASE_NODE_IMAGE: ${BASE_NODE_IMAGE:-node:20-slim}
        BASE_NGINX_IMAGE: ${BASE_NGINX_IMAGE:-nginx:1.27-alpine}
    container_name: mitv-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
